# Generated by Django 2.2.25 on 2022-12-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Movie'), (2, 'Planet')])),
                ('item', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
